// <auto-generated />
using Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220130143619_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("isBusy")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Джоан Роулінг",
                            genre = "Фентезі",
                            isBusy = true,
                            title = "Гаррі Потер і філософський камінь",
                            year = 2000
                        },
                        new
                        {
                            id = 2,
                            author = "Антон Карелин",
                            genre = "Детектив",
                            isBusy = false,
                            title = "Миллион миров",
                            year = 2022
                        },
                        new
                        {
                            id = 3,
                            author = "Дмитрий Билик",
                            genre = "Пригоди",
                            isBusy = true,
                            title = "Уникум 1: Тайная дверь",
                            year = 2010
                        },
                        new
                        {
                            id = 4,
                            author = "Макс Вальтер",
                            genre = "Пригоди",
                            isBusy = true,
                            title = "Смерть может танцевать",
                            year = 2020
                        },
                        new
                        {
                            id = 5,
                            author = "Касымов Тимур",
                            genre = "Поезія",
                            isBusy = false,
                            title = "Важный разговор",
                            year = 2000
                        },
                        new
                        {
                            id = 6,
                            author = "Дмитрий Виз",
                            genre = "Поезія",
                            isBusy = false,
                            title = "Свин Бося . Гоню",
                            year = 2000
                        },
                        new
                        {
                            id = 7,
                            author = "Mastadont аkа Aveolin",
                            genre = "Фентезі",
                            isBusy = false,
                            title = "Викинг",
                            year = 2000
                        },
                        new
                        {
                            id = 8,
                            author = "Александр Якубович",
                            genre = "Пригоди",
                            isBusy = true,
                            title = "Ученик Рун",
                            year = 2001
                        },
                        new
                        {
                            id = 9,
                            author = "Андрей Васильев",
                            genre = "Фентезі",
                            isBusy = true,
                            title = "Карусель теней",
                            year = 2000
                        },
                        new
                        {
                            id = 10,
                            author = "Джоан Роулінг",
                            genre = "Фентезі",
                            isBusy = true,
                            title = "Гаррі Потер і таємна кімната",
                            year = 2000
                        },
                        new
                        {
                            id = 11,
                            author = "Джоан Роулінг",
                            genre = "Фентезі",
                            isBusy = true,
                            title = "Гаррі Потер і келих вогню",
                            year = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
